export const CANDLE_CONFIGS = {
    SCREEN_ASPECT_RATIO: 16 / 11,
    CONTENT_ASPECT_RATIO: 16 / 9,
    Y_WIDTH: 60,
    X_HEIGHT: 30,
    TICK_WIDTH: 10,
    TIME_UNITS_ON_SCREEN: 5,
    PRICE_WIDTH: 10,
    PRICE_UNIT_HEIGHT: 5,
    PRICE_UNITS_ON_SCREEN: 5,
    PRICE_PADDING_IN_PERCENTAGES: 10,
    PRICE_PADDING: 0,
}